Lagt til flagg for behandling i ny saksbehandling
navikt/familie-ef-mottak pull request #485
Opened 2021-04-16 12:57 UTC by blommish

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4347

CoAuthor @neringaalt

2021-04-19 05:01 UTC, charliemidtlyng approved these changes

2021-04-19 13:54 UTC, ma10s requested changes
Vi kan nesten ikke sette "førstegangsbehandling" på alle -> en ekstre sjekk i if som setter behandlesAvApplikasjon burde holde :)

2021-04-19 13:54 UTC, ma10s commented on src/main/kotlin/no/nav/familie/ef/mottak/service/OppgaveService.kt
> +        val behandlesAvApplikasjon = if (søknad.behandleINySaksbehandling) "familie-ef-sak-førstegangsbehandling" else null
Her trenger vi også en sjekk på om denne "kunne blitt behandlet i infotrygd" 
:)

2021-04-20 05:17 UTC, charliemidtlyng commented on src/main/kotlin/no/nav/familie/ef/mottak/service/OppgaveService.kt
> +        val behandlesAvApplikasjon = if (søknad.behandleINySaksbehandling) "familie-ef-sak-førstegangsbehandling" else null
Godt observert!

2021-04-20 07:23 UTC, ma10s approved these changes

2021-04-20 12:50 UTC, merged