Endret post til get.
navikt/familie-ef-mottak pull request #636
Opened 2021-11-04 09:48 UTC by bent-lorentzen

2021-11-04 12:15 UTC, blommish approved these changes

2021-11-05 09:08 UTC, charliemidtlyng commented on src/main/kotlin/no/nav/familie/ef/mottak/integration/IntegrasjonerClient.kt
> +                .queryParams(finnMappeRequest.toQueryParams())
Test denne i preprod først :) Bare å åpne oppgavebenken så ser du om enhetsmappene kommer opp i nedtrekkslisten på filtrering

2021-11-05 09:16 UTC, charliemidtlyng requested changes
Dette vil ikke funke;
```    "melding": "Det oppstod en feil. Failed to instantiate [no.nav.familie.kontrakter.felles.oppgave.FinnMappeRequest]: Constructor threw exception; nested exception is java.lang.NullPointerException: Parameter specified as non-null is null: method no.nav.familie.kontrakter.felles.oppgave.FinnMappeRequest.<init>, parameter tema",
```

Det er spesifisert et non-nullable objekt i integrasjoner, men det er ikke mulig å sende i et "GET-request" uten ekstremt tvilsom mikkmakk. Integrasjoner må isåfall endres til å ha nullable queryParams for disse feltene

2021-11-05 13:33 UTC, bent-lorentzen commented
> Dette vil ikke funke;
> 
> ```
> "melding": "Det oppstod en feil. Failed to instantiate [no.nav.familie.kontrakter.felles.oppgave.FinnMappeRequest]: Constructor threw exception; nested exception is java.lang.NullPointerException: Parameter specified as non-null is null: method no.nav.familie.kontrakter.felles.oppgave.FinnMappeRequest.<init>, parameter tema",
> ```
> 
> Det er spesifisert et non-nullable objekt i integrasjoner, men det er ikke mulig å sende i et "GET-request" uten ekstremt tvilsom mikkmakk. Integrasjoner må isåfall endres til å ha nullable queryParams for disse feltene

Jeg vet det, det er derfor det lå en PR i kontrakter på å fikse det, som jeg har merget nå. :)

2021-11-05 14:10 UTC, charliemidtlyng approved these changes

2021-11-05 14:10 UTC, charliemidtlyng commented
Supert! Da funker det nok

2021-11-09 12:51 UTC, merged